# backend deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment  
spec:
  replicas: 2
  selector:
    app: backend
  template: 
    metadata:
      labels:
        app: backend
    spec: 
      containers:
      - name: backend
        image: backend:latest
        ports:
          containers:
            - name: backend
            - image: hritikraj003/todo-backend
            ports:
              - containerPort: 8080
            

---
# backend-service
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  

        